sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - tree

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - "7"

before_script:
  - echo "pwd=$PWD"
  - LATEST=$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE) ; wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip && sudo ln -s $PWD/chromedriver /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - yarn test:travis
